# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

trigger:
 - master

resources:
  repositories:
    - repository: rcoalescence
      type: github
      name: thompsonsed/rcoalescence
      endpoint: thompsonsed

jobs:
  - template: .azure/azure-rcoalescence.yml@rcoalescence
