parameters:
  R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
  CRAN: 'https://cloud.r-project.org'
  coverage: true
  env: {}

jobs:
  - job: 'Linux'
    variables:
      CRAN: 'https://demo.rstudiopm.com/all/__linux__/xenial/latest'
      R_LIBS_USER: ${{parameters.R_LIBS_USER}}
      TZ: UTC
      CI: true
      ${{ insert }}: ${{ parameters.env }}
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        R-3.2:
          containerImage: rstudio/r-base:3.2-xenial
        R-3.3:
          containerImage: rstudio/r-base:3.3-xenial
        R-3.4:
          containerImage: rstudio/r-base:3.4-xenial
        R-3.5:
          containerImage: rstudio/r-base:3.5-xenial
        R-3.6:
          containerImage: rstudio/r-base:3.6-xenial
    container: $[ variables['containerImage'] ]
    steps:
      - template: templates/r-setup-linux.yml
      - template: templates/pkg-workflow.yml
        parameters:
          coverage: false


  - job: 'macOS'
    variables:
      CRAN: ${{parameters.CRAN}}
      R_LIBS_USER: ${{parameters.R_LIBS_USER}}
      CI: true
      ${{ insert }}: ${{ parameters.env }}
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: templates/r-setup-macOS.yml
      - template: templates/pkg-workflow.yml
        parameters:
          coverage: ${{parameters.coverage}}

  - job: 'Windows'
    variables:
      CRAN: ${{parameters.CRAN}}
      R_LIBS_USER: ${{parameters.R_LIBS_USER}}
      CI: true
      ${{ insert }}: ${{ parameters.env }}
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: templates/r-setup-windows.yml
      - template: templates/pkg-workflow.yml
        parameters:
          args: "c('--no-manual', '--no-multiarch')"
          coverage: false
          cache: false
